const smartphoneData = {
  "Combined Data": [
    {
      "Brand": "Samsung",
      "Model": "Galaxy S25 Ultra",
      "Price (₹)": "93,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 99,
      "Camera Score": 98,
      "Battery Score": 89
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S25+",
      "Price (₹)": "79,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4900mAh",
      "Gaming Score": 98,
      "Camera Score": 92,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S25",
      "Price (₹)": "58,749",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4000mAh",
      "Gaming Score": 97,
      "Camera Score": 90,
      "Battery Score": 76
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S24 Ultra",
      "Price (₹)": "69,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 96,
      "Camera Score": 97,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S24+",
      "Price (₹)": "59,999",
      "Processor": "Exynos 2400",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4900mAh",
      "Gaming Score": 89,
      "Camera Score": 90,
      "Battery Score": 87
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S24",
      "Price (₹)": "45,999",
      "Processor": "Exynos 2400",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "4000mAh",
      "Gaming Score": 88,
      "Camera Score": 88,
      "Battery Score": 75
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy A56 5G",
      "Price (₹)": "38,999",
      "Processor": "Exynos 1580",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 76,
      "Camera Score": 82,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy A36 5G",
      "Price (₹)": "28,315",
      "Processor": "Snapdragon 6 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 71,
      "Camera Score": 75,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy A26 5G",
      "Price (₹)": "23,499",
      "Processor": "Exynos 1380",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 66,
      "Camera Score": 70,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy S24 FE",
      "Price (₹)": "39,999",
      "Processor": "Exynos 2400e",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "4700mAh",
      "Gaming Score": 85,
      "Camera Score": 86,
      "Battery Score": 84
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy Z Fold6",
      "Price (₹)": "78,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4400mAh",
      "Gaming Score": 95,
      "Camera Score": 91,
      "Battery Score": 77
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 16 Pro",
      "Price (₹)": "85,999",
      "Processor": "A18 Pro",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "3582mAh",
      "Gaming Score": 98,
      "Camera Score": 97,
      "Battery Score": 79
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 16 Plus",
      "Price (₹)": "79,900",
      "Processor": "A18",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "4674mAh",
      "Gaming Score": 94,
      "Camera Score": 88,
      "Battery Score": 94
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 16",
      "Price (₹)": "69,900*",
      "Processor": "A18",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "3561mAh",
      "Gaming Score": 94,
      "Camera Score": 88,
      "Battery Score": 80
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 16e",
      "Price (₹)": "44,327",
      "Processor": "A18",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "4005mAh",
      "Gaming Score": 92,
      "Camera Score": 80,
      "Battery Score": 86
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 15 Pro Max",
      "Price (₹)": "99,000*",
      "Processor": "A17 Pro",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "4441mAh",
      "Gaming Score": 95,
      "Camera Score": 96,
      "Battery Score": 88
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 15 Pro",
      "Price (₹)": "89,000*",
      "Processor": "A17 Pro",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "3274mAh",
      "Gaming Score": 94,
      "Camera Score": 95,
      "Battery Score": 74
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 15 Plus",
      "Price (₹)": "69,000*",
      "Processor": "A16 Bionic",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "4383mAh",
      "Gaming Score": 88,
      "Camera Score": 86,
      "Battery Score": 91
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 15",
      "Price (₹)": "59,000*",
      "Processor": "A16 Bionic",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "3349mAh",
      "Gaming Score": 87,
      "Camera Score": 85,
      "Battery Score": 76
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 14",
      "Price (₹)": "49,000*",
      "Processor": "A15 Bionic",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "3279mAh",
      "Gaming Score": 82,
      "Camera Score": 80,
      "Battery Score": 75
    },
    {
      "Brand": "OnePlus",
      "Model": "OnePlus 13",
      "Price (₹)": "69,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 99,
      "Camera Score": 93,
      "Battery Score": 97
    },
    {
      "Brand": "OnePlus",
      "Model": "OnePlus 13s",
      "Price (₹)": "54,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5850mAh",
      "Gaming Score": 98,
      "Camera Score": 88,
      "Battery Score": 96
    },
    {
      "Brand": "OnePlus",
      "Model": "OnePlus 13R",
      "Price (₹)": "42,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 94,
      "Camera Score": 84,
      "Battery Score": 97
    },
    {
      "Brand": "OnePlus",
      "Model": "OnePlus Open",
      "Price (₹)": "99,999",
      "Processor": "Snapdragon 8 Gen 2",
      "RAM": "16GB",
      "Storage": "512GB",
      "Battery": "4805mAh",
      "Gaming Score": 91,
      "Camera Score": 92,
      "Battery Score": 85
    },
    {
      "Brand": "OnePlus",
      "Model": "Nord CE 5",
      "Price (₹)": "24,999",
      "Processor": "Dimensity 8350",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "7100mAh",
      "Gaming Score": 79,
      "Camera Score": 75,
      "Battery Score": 100
    },
    {
      "Brand": "OnePlus",
      "Model": "Nord CE 4 Lite",
      "Price (₹)": "17,999",
      "Processor": "Snapdragon 695",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5500mAh",
      "Gaming Score": 58,
      "Camera Score": 62,
      "Battery Score": 92
    },
    {
      "Brand": "OnePlus",
      "Model": "Nord CE 4",
      "Price (₹)": "24,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 82,
      "Camera Score": 76,
      "Battery Score": 92
    },
    {
      "Brand": "Google",
      "Model": "Pixel 9",
      "Price (₹)": "74,999",
      "Processor": "Tensor G4",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4700mAh",
      "Gaming Score": 76,
      "Camera Score": 95,
      "Battery Score": 86
    },
    {
      "Brand": "Google",
      "Model": "Pixel 9a",
      "Price (₹)": "49,999",
      "Processor": "Tensor G4",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5100mAh",
      "Gaming Score": 74,
      "Camera Score": 88,
      "Battery Score": 92
    },
    {
      "Brand": "Google",
      "Model": "Pixel 8a",
      "Price (₹)": "37,999",
      "Processor": "Tensor G3",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "4492mAh",
      "Gaming Score": 68,
      "Camera Score": 86,
      "Battery Score": 82
    },
    {
      "Brand": "Google",
      "Model": "Pixel 8",
      "Price (₹)": "54,999",
      "Processor": "Tensor G3",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "4575mAh",
      "Gaming Score": 69,
      "Camera Score": 92,
      "Battery Score": 83
    },
    {
      "Brand": "Google",
      "Model": "Pixel 8 Pro",
      "Price (₹)": "79,999",
      "Processor": "Tensor G3",
      "RAM": "12GB",
      "Storage": "128GB",
      "Battery": "5050mAh",
      "Gaming Score": 71,
      "Camera Score": 97,
      "Battery Score": 91
    },
    {
      "Brand": "Google",
      "Model": "Pixel Fold",
      "Price (₹)": "89,999",
      "Processor": "Tensor G2",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4821mAh",
      "Gaming Score": 63,
      "Camera Score": 90,
      "Battery Score": 85
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 60 Fusion",
      "Price (₹)": "22,999",
      "Processor": "Dimensity 7400",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 76,
      "Camera Score": 80,
      "Battery Score": 92
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 50 Ultra",
      "Price (₹)": "49,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "4500mAh",
      "Gaming Score": 88,
      "Camera Score": 92,
      "Battery Score": 80
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 50 Pro",
      "Price (₹)": "29,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "4500mAh",
      "Gaming Score": 78,
      "Camera Score": 87,
      "Battery Score": 80
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 50 Fusion",
      "Price (₹)": "20,999",
      "Processor": "Snapdragon 7s Gen 2",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 72,
      "Camera Score": 78,
      "Battery Score": 88
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 50 Neo",
      "Price (₹)": "22,999",
      "Processor": "Dimensity 7300",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "4310mAh",
      "Gaming Score": 71,
      "Camera Score": 84,
      "Battery Score": 76
    },
    {
      "Brand": "Motorola",
      "Model": "Razr 50 Ultra",
      "Price (₹)": "79,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "4000mAh",
      "Gaming Score": 87,
      "Camera Score": 88,
      "Battery Score": 72
    },
    {
      "Brand": "Motorola",
      "Model": "Razr 50",
      "Price (₹)": "54,999",
      "Processor": "Dimensity 7300X",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "4200mAh",
      "Gaming Score": 73,
      "Camera Score": 82,
      "Battery Score": 75
    },
    {
      "Brand": "Motorola",
      "Model": "Moto G85 5G",
      "Price (₹)": "17,999",
      "Processor": "Snapdragon 6s Gen 3",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 62,
      "Camera Score": 70,
      "Battery Score": 88
    },
    {
      "Brand": "Motorola",
      "Model": "Moto G45 5G",
      "Price (₹)": "10,999",
      "Processor": "Snapdragon 6s Gen 3",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 61,
      "Camera Score": 65,
      "Battery Score": 88
    },
    {
      "Brand": "Motorola",
      "Model": "Moto G35 5G",
      "Price (₹)": "9,999",
      "Processor": "Unisoc T760",
      "RAM": "4GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 48,
      "Camera Score": 58,
      "Battery Score": 88
    },
    {
      "Brand": "Nothing",
      "Model": "Phone 3",
      "Price (₹)": "54,999",
      "Processor": "Snapdragon 8s Gen 4",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5150mAh",
      "Gaming Score": 91,
      "Camera Score": 88,
      "Battery Score": 90
    },
    {
      "Brand": "CMF",
      "Model": "Phone 2 Pro",
      "Price (₹)": "18,999",
      "Processor": "Dimensity 7300 Pro",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 74,
      "Camera Score": 75,
      "Battery Score": 88
    },
    {
      "Brand": "CMF",
      "Model": "Phone 1",
      "Price (₹)": "14,999",
      "Processor": "Dimensity 7300",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 72,
      "Camera Score": 68,
      "Battery Score": 88
    },
    {
      "Brand": "Vivo",
      "Model": "X200 Pro",
      "Price (₹)": "94,999",
      "Processor": "Dimensity 9400",
      "RAM": "16GB",
      "Storage": "512GB",
      "Battery": "6000mAh",
      "Gaming Score": 98,
      "Camera Score": 99,
      "Battery Score": 97
    },
    {
      "Brand": "Vivo",
      "Model": "X200",
      "Price (₹)": "65,999",
      "Processor": "Dimensity 9400",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5800mAh",
      "Gaming Score": 97,
      "Camera Score": 92,
      "Battery Score": 96
    },
    {
      "Brand": "Vivo",
      "Model": "X Fold3 Pro",
      "Price (₹)": "1,49,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "16GB",
      "Storage": "512GB",
      "Battery": "5700mAh",
      "Gaming Score": 95,
      "Camera Score": 95,
      "Battery Score": 95
    },
    {
      "Brand": "Vivo",
      "Model": "V50",
      "Price (₹)": "34,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 81,
      "Camera Score": 86,
      "Battery Score": 98
    },
    {
      "Brand": "Vivo",
      "Model": "V40 Pro",
      "Price (₹)": "41,999",
      "Processor": "Dimensity 9200+",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 89,
      "Camera Score": 90,
      "Battery Score": 92
    },
    {
      "Brand": "Vivo",
      "Model": "V40",
      "Price (₹)": "29,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 80,
      "Camera Score": 84,
      "Battery Score": 92
    },
    {
      "Brand": "Vivo",
      "Model": "T3 Ultra",
      "Price (₹)": "31,999",
      "Processor": "Dimensity 9200+",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 90,
      "Camera Score": 82,
      "Battery Score": 92
    },
    {
      "Brand": "Vivo",
      "Model": "T3 Pro",
      "Price (₹)": "24,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 81,
      "Camera Score": 78,
      "Battery Score": 92
    },
    {
      "Brand": "Vivo",
      "Model": "Y300 Plus",
      "Price (₹)": "22,999",
      "Processor": "Snapdragon 695",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 58,
      "Camera Score": 68,
      "Battery Score": 88
    },
    {
      "Brand": "iQOO",
      "Model": "12",
      "Price (₹)": "49,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 96,
      "Camera Score": 89,
      "Battery Score": 88
    },
    {
      "Brand": "iQOO",
      "Model": "Neo 10",
      "Price (₹)": "34,999",
      "Processor": "Snapdragon 8s Gen 4",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "7000mAh",
      "Gaming Score": 97,
      "Camera Score": 80,
      "Battery Score": 100
    },
    {
      "Brand": "iQOO",
      "Model": "Z10",
      "Price (₹)": "21,999",
      "Processor": "Snapdragon 7s Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "7300mAh",
      "Gaming Score": 78,
      "Camera Score": 70,
      "Battery Score": 100
    },
    {
      "Brand": "iQOO",
      "Model": "Z9s Pro",
      "Price (₹)": "24,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 81,
      "Camera Score": 77,
      "Battery Score": 92
    },
    {
      "Brand": "iQOO",
      "Model": "Z9s",
      "Price (₹)": "19,999",
      "Processor": "Dimensity 7300",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5500mAh",
      "Gaming Score": 74,
      "Camera Score": 74,
      "Battery Score": 92
    },
    {
      "Brand": "iQOO",
      "Model": "Z9 Lite",
      "Price (₹)": "10,499",
      "Processor": "Dimensity 6300",
      "RAM": "4GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 52,
      "Camera Score": 58,
      "Battery Score": 88
    },
    {
      "Brand": "iQOO",
      "Model": "Z9",
      "Price (₹)": "17,999",
      "Processor": "Dimensity 7200",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 76,
      "Camera Score": 72,
      "Battery Score": 88
    },
    {
      "Brand": "OPPO",
      "Model": "Find X8 Pro",
      "Price (₹)": "99,999",
      "Processor": "Dimensity 9400",
      "RAM": "16GB",
      "Storage": "512GB",
      "Battery": "5910mAh",
      "Gaming Score": 98,
      "Camera Score": 98,
      "Battery Score": 97
    },
    {
      "Brand": "OPPO",
      "Model": "Find X8",
      "Price (₹)": "69,999",
      "Processor": "Dimensity 9400",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5630mAh",
      "Gaming Score": 97,
      "Camera Score": 92,
      "Battery Score": 94
    },
    {
      "Brand": "OPPO",
      "Model": "Reno 14 Pro",
      "Price (₹)": "49,999",
      "Processor": "Dimensity 8450",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6200mAh",
      "Gaming Score": 86,
      "Camera Score": 90,
      "Battery Score": 99
    },
    {
      "Brand": "OPPO",
      "Model": "Reno 14",
      "Price (₹)": "37,999",
      "Processor": "Dimensity 8350",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 82,
      "Camera Score": 84,
      "Battery Score": 97
    },
    {
      "Brand": "OPPO",
      "Model": "Reno 13 Pro",
      "Price (₹)": "44,999",
      "Processor": "Dimensity 8350",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5800mAh",
      "Gaming Score": 84,
      "Camera Score": 88,
      "Battery Score": 95
    },
    {
      "Brand": "OPPO",
      "Model": "Reno 13",
      "Price (₹)": "34,999",
      "Processor": "Dimensity 8350",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5600mAh",
      "Gaming Score": 82,
      "Camera Score": 82,
      "Battery Score": 93
    },
    {
      "Brand": "OPPO",
      "Model": "F29 Pro",
      "Price (₹)": "29,999",
      "Processor": "Dimensity 7300 Energy",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 74,
      "Camera Score": 78,
      "Battery Score": 97
    },
    {
      "Brand": "OPPO",
      "Model": "F29",
      "Price (₹)": "24,999",
      "Processor": "Snapdragon 6 Gen 1",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "6500mAh",
      "Gaming Score": 66,
      "Camera Score": 72,
      "Battery Score": 100
    },
    {
      "Brand": "OPPO",
      "Model": "K13",
      "Price (₹)": "17,999",
      "Processor": "Snapdragon 6 Gen 4",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "7000mAh",
      "Gaming Score": 70,
      "Camera Score": 68,
      "Battery Score": 100
    },
    {
      "Brand": "Xiaomi",
      "Model": "Xiaomi 14 Ultra",
      "Price (₹)": "99,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "16GB",
      "Storage": "512GB",
      "Battery": "5300mAh",
      "Gaming Score": 97,
      "Camera Score": 99,
      "Battery Score": 91
    },
    {
      "Brand": "Xiaomi",
      "Model": "Xiaomi 14",
      "Price (₹)": "64,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "4610mAh",
      "Gaming Score": 96,
      "Camera Score": 94,
      "Battery Score": 82
    },
    {
      "Brand": "Redmi",
      "Model": "Note 14 Pro+",
      "Price (₹)": "31,999",
      "Processor": "Snapdragon 7s Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6200mAh",
      "Gaming Score": 81,
      "Camera Score": 84,
      "Battery Score": 99
    },
    {
      "Brand": "Redmi",
      "Model": "Note 14 Pro",
      "Price (₹)": "27,999",
      "Processor": "Dimensity 7300 Ultra",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 75,
      "Camera Score": 81,
      "Battery Score": 92
    },
    {
      "Brand": "Redmi",
      "Model": "14C 5G",
      "Price (₹)": "10,999",
      "Processor": "Snapdragon 4 Gen 2",
      "RAM": "4GB",
      "Storage": "128GB",
      "Battery": "5160mAh",
      "Gaming Score": 55,
      "Camera Score": 60,
      "Battery Score": 89
    },
    {
      "Brand": "Redmi",
      "Model": "A4 5G",
      "Price (₹)": "8,999",
      "Processor": "Snapdragon 4s Gen 2",
      "RAM": "4GB",
      "Storage": "64GB",
      "Battery": "5160mAh",
      "Gaming Score": 50,
      "Camera Score": 56,
      "Battery Score": 89
    },
    {
      "Brand": "Redmi",
      "Model": "A5",
      "Price (₹)": "6,999",
      "Processor": "Unisoc T7250",
      "RAM": "4GB",
      "Storage": "64GB",
      "Battery": "5000mAh",
      "Gaming Score": 42,
      "Camera Score": 50,
      "Battery Score": 88
    },
    {
      "Brand": "POCO",
      "Model": "F7 Ultra",
      "Price (₹)": "59,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5300mAh",
      "Gaming Score": 100,
      "Camera Score": 90,
      "Battery Score": 91
    },
    {
      "Brand": "POCO",
      "Model": "F7 Pro",
      "Price (₹)": "44,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 96,
      "Camera Score": 84,
      "Battery Score": 97
    },
    {
      "Brand": "POCO",
      "Model": "X7 Pro",
      "Price (₹)": "29,999",
      "Processor": "Dimensity 8400 Ultra",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6550mAh",
      "Gaming Score": 91,
      "Camera Score": 78,
      "Battery Score": 100
    },
    {
      "Brand": "POCO",
      "Model": "X7",
      "Price (₹)": "22,999",
      "Processor": "Dimensity 7300 Ultra",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 75,
      "Camera Score": 74,
      "Battery Score": 92
    },
    {
      "Brand": "POCO",
      "Model": "M7 Pro 5G",
      "Price (₹)": "14,999",
      "Processor": "Dimensity 7025 Ultra",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5110mAh",
      "Gaming Score": 66,
      "Camera Score": 68,
      "Battery Score": 89
    },
    {
      "Brand": "POCO",
      "Model": "C71",
      "Price (₹)": "6,999",
      "Processor": "Unisoc T7250",
      "RAM": "4GB",
      "Storage": "64GB",
      "Battery": "5200mAh",
      "Gaming Score": 42,
      "Camera Score": 50,
      "Battery Score": 89
    },
    {
      "Brand": "Realme",
      "Model": "GT 7",
      "Price (₹)": "39,999",
      "Processor": "Dimensity 9400e",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "7000mAh",
      "Gaming Score": 98,
      "Camera Score": 88,
      "Battery Score": 100
    },
    {
      "Brand": "Realme",
      "Model": "GT 7 Pro",
      "Price (₹)": "59,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "6500mAh",
      "Gaming Score": 100,
      "Camera Score": 92,
      "Battery Score": 99
    },
    {
      "Brand": "Realme",
      "Model": "P3 Ultra",
      "Price (₹)": "29,999",
      "Processor": "Dimensity 8350 Ultra",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 85,
      "Camera Score": 78,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "P3 Pro",
      "Price (₹)": "23,999",
      "Processor": "Snapdragon 7s Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 78,
      "Camera Score": 74,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "P3",
      "Price (₹)": "16,999",
      "Processor": "Snapdragon 6 Gen 4",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "6000mAh",
      "Gaming Score": 68,
      "Camera Score": 68,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "14 Pro+",
      "Price (₹)": "32,999",
      "Processor": "Snapdragon 7s Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 79,
      "Camera Score": 86,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "14 Pro",
      "Price (₹)": "26,999",
      "Processor": "Dimensity 7300 Energy",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 74,
      "Camera Score": 80,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "14x",
      "Price (₹)": "14,999",
      "Processor": "Dimensity 6300",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "6000mAh",
      "Gaming Score": 56,
      "Camera Score": 62,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "Narzo 80 Pro",
      "Price (₹)": "19,999",
      "Processor": "Dimensity 7400",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "6000mAh",
      "Gaming Score": 77,
      "Camera Score": 72,
      "Battery Score": 97
    },
    {
      "Brand": "Realme",
      "Model": "Narzo 80x",
      "Price (₹)": "13,999",
      "Processor": "Dimensity 6400",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "6000mAh",
      "Gaming Score": 61,
      "Camera Score": 65,
      "Battery Score": 97
    },
    {
      "Brand": "Honor",
      "Model": "Magic6 Pro",
      "Price (₹)": "89,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "5600mAh",
      "Gaming Score": 96,
      "Camera Score": 98,
      "Battery Score": 94
    },
    {
      "Brand": "Honor",
      "Model": "400 Pro",
      "Price (₹)": "54,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "6000mAh",
      "Gaming Score": 96,
      "Camera Score": 91,
      "Battery Score": 98
    },
    {
      "Brand": "Honor",
      "Model": "400",
      "Price (₹)": "34,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 81,
      "Camera Score": 84,
      "Battery Score": 98
    },
    {
      "Brand": "Infinix",
      "Model": "GT 30 Pro",
      "Price (₹)": "24,999",
      "Processor": "Dimensity 8350 Ultimate",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5500mAh",
      "Gaming Score": 87,
      "Camera Score": 75,
      "Battery Score": 92
    },
    {
      "Brand": "Infinix",
      "Model": "Zero 40 5G",
      "Price (₹)": "29,999",
      "Processor": "Dimensity 8200 Ultimate",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 84,
      "Camera Score": 82,
      "Battery Score": 88
    },
    {
      "Brand": "Infinix",
      "Model": "Note 40 Pro 5G",
      "Price (₹)": "21,999",
      "Processor": "Dimensity 7020",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 66,
      "Camera Score": 72,
      "Battery Score": 88
    },
    {
      "Brand": "Tecno",
      "Model": "Camon 40 Premier",
      "Price (₹)": "39,999",
      "Processor": "Dimensity 8350",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "5100mAh",
      "Gaming Score": 86,
      "Camera Score": 90,
      "Battery Score": 89
    },
    {
      "Brand": "Tecno",
      "Model": "Camon 40 Pro",
      "Price (₹)": "24,999",
      "Processor": "Dimensity 7300",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5200mAh",
      "Gaming Score": 74,
      "Camera Score": 82,
      "Battery Score": 90
    },
    {
      "Brand": "Tecno",
      "Model": "Pova 7 Pro",
      "Price (₹)": "19,999",
      "Processor": "Dimensity 7300",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "6000mAh",
      "Gaming Score": 76,
      "Camera Score": 70,
      "Battery Score": 97
    },
    {
      "Brand": "Tecno",
      "Model": "Phantom V Fold 2",
      "Price (₹)": "99,999",
      "Processor": "Dimensity 9000+",
      "RAM": "12GB",
      "Storage": "512GB",
      "Battery": "5750mAh",
      "Gaming Score": 89,
      "Camera Score": 88,
      "Battery Score": 95
    },
    {
      "Brand": "Lava",
      "Model": "Agni 3",
      "Price (₹)": "24,999",
      "Processor": "Dimensity 7300X",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 75,
      "Camera Score": 80,
      "Battery Score": 88
    },
    {
      "Brand": "Lava",
      "Model": "Blaze Duo 5G",
      "Price (₹)": "18,999",
      "Processor": "Dimensity 7025",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 66,
      "Camera Score": 68,
      "Battery Score": 88
    },
    {
      "Brand": "Lava",
      "Model": "Blaze Curve 5G",
      "Price (₹)": "16,999",
      "Processor": "Dimensity 7050",
      "RAM": "8GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 70,
      "Camera Score": 72,
      "Battery Score": 88
    },
    {
      "Brand": "HMD",
      "Model": "Skyline",
      "Price (₹)": "35,999",
      "Processor": "Snapdragon 7s Gen 2",
      "RAM": "12GB",
      "Storage": "256GB",
      "Battery": "4600mAh",
      "Gaming Score": 74,
      "Camera Score": 84,
      "Battery Score": 82
    },
    {
      "Brand": "HMD",
      "Model": "Fusion",
      "Price (₹)": "19,999",
      "Processor": "Snapdragon 4 Gen 2",
      "RAM": "8GB",
      "Storage": "256GB",
      "Battery": "5000mAh",
      "Gaming Score": 56,
      "Camera Score": 68,
      "Battery Score": 88
    },
    {
      "Brand": "HMD",
      "Model": "Crest 5G",
      "Price (₹)": "14,999",
      "Processor": "Unisoc T760",
      "RAM": "6GB",
      "Storage": "128GB",
      "Battery": "5000mAh",
      "Gaming Score": 52,
      "Camera Score": 65,
      "Battery Score": 88
    },
    {
      "Brand": "Xiaomi",
      "Model": "Redmi 12 5G",
      "Price (₹)": "10,999",
      "Processor": "Snapdragon 4 Gen 2",
      "RAM": "4-8 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 70,
      "Camera Score": 65,
      "Battery Score": 75
    },
    {
      "Brand": "Vivo",
      "Model": "T5 Lite 5G",
      "Price (₹)": "11,999",
      "Processor": "Dimensity 6300",
      "RAM": "4-8 GB",
      "Storage": "128-256 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 74,
      "Camera Score": 68,
      "Battery Score": 90
    },
    {
      "Brand": "Realme",
      "Model": "C65 5G",
      "Price (₹)": "10,499",
      "Processor": "Dimensity 6300",
      "RAM": "4-6 GB",
      "Storage": "64-128 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 72,
      "Camera Score": 66,
      "Battery Score": 75
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy M15 5G",
      "Price (₹)": "12,999",
      "Processor": "Dimensity 6100+",
      "RAM": "4-8 GB",
      "Storage": "128 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 74,
      "Camera Score": 70,
      "Battery Score": 90
    },
    {
      "Brand": "POCO",
      "Model": "C65",
      "Price (₹)": "7,999",
      "Processor": "Helio G85",
      "RAM": "4-8 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 65,
      "Camera Score": 62,
      "Battery Score": 75
    },
    {
      "Brand": "Lava",
      "Model": "Blaze 3X 5G",
      "Price (₹)": "11,499",
      "Processor": "Dimensity 6300",
      "RAM": "4-8 GB",
      "Storage": "128 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 73,
      "Camera Score": 68,
      "Battery Score": 75
    },
    {
      "Brand": "itel",
      "Model": "P55 5G",
      "Price (₹)": "9,999",
      "Processor": "Dimensity 6080",
      "RAM": "4-6 GB",
      "Storage": "128 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 71,
      "Camera Score": 60,
      "Battery Score": 75
    },
    {
      "Brand": "Vivo",
      "Model": "T4X 5G",
      "Price (₹)": "13,999",
      "Processor": "Dimensity 7300",
      "RAM": "6-8 GB",
      "Storage": "128-256 GB",
      "Battery": "6500 mAh",
      "Gaming Score": 82,
      "Camera Score": 72,
      "Battery Score": 95
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy A35 5G",
      "Price (₹)": "24,999",
      "Processor": "Exynos 1380",
      "RAM": "8 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 80,
      "Camera Score": 84,
      "Battery Score": 78
    },
    {
      "Brand": "Realme",
      "Model": "Narzo 70 Turbo",
      "Price (₹)": "16,999",
      "Processor": "Dimensity 7300 Energy",
      "RAM": "6-12 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 88,
      "Camera Score": 75,
      "Battery Score": 78
    },
    {
      "Brand": "Motorola",
      "Model": "Moto G64 5G",
      "Price (₹)": "14,999",
      "Processor": "Dimensity 7025",
      "RAM": "8-12 GB",
      "Storage": "128-256 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 80,
      "Camera Score": 72,
      "Battery Score": 90
    },
    {
      "Brand": "POCO",
      "Model": "M6 Pro 5G",
      "Price (₹)": "9,999",
      "Processor": "Snapdragon 4 Gen 2",
      "RAM": "4-8 GB",
      "Storage": "64-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 72,
      "Camera Score": 65,
      "Battery Score": 75
    },
    {
      "Brand": "Xiaomi",
      "Model": "Redmi Note 14 5G",
      "Price (₹)": "18,999",
      "Processor": "Dimensity 7025 Ultra",
      "RAM": "6-8 GB",
      "Storage": "128-256 GB",
      "Battery": "5110 mAh",
      "Gaming Score": 82,
      "Camera Score": 80,
      "Battery Score": 82
    },
    {
      "Brand": "Infinix",
      "Model": "Note 50 Pro",
      "Price (₹)": "21,999",
      "Processor": "Helio G100",
      "RAM": "8-12 GB",
      "Storage": "256 GB",
      "Battery": "5200 mAh",
      "Gaming Score": 80,
      "Camera Score": 78,
      "Battery Score": 85
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy F15 5G",
      "Price (₹)": "13,999",
      "Processor": "Dimensity 6100+",
      "RAM": "4-8 GB",
      "Storage": "128 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 74,
      "Camera Score": 70,
      "Battery Score": 90
    },
    {
      "Brand": "iQOO",
      "Model": "Z10x 5G",
      "Price (₹)": "14,999",
      "Processor": "Dimensity 7300",
      "RAM": "6-8 GB",
      "Storage": "128-256 GB",
      "Battery": "6500 mAh",
      "Gaming Score": 84,
      "Camera Score": 72,
      "Battery Score": 95
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy M35 5G",
      "Price (₹)": "18,999",
      "Processor": "Exynos 1380",
      "RAM": "6-8 GB",
      "Storage": "128-256 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 82,
      "Camera Score": 80,
      "Battery Score": 90
    },
    {
      "Brand": "Nothing",
      "Model": "Phone 3a Pro",
      "Price (₹)": "29,999",
      "Processor": "Snapdragon 7s Gen 3",
      "RAM": "12 GB",
      "Storage": "256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 87,
      "Camera Score": 88,
      "Battery Score": 78
    },
    {
      "Brand": "iQOO",
      "Model": "Neo 10R",
      "Price (₹)": "26,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "8-12 GB",
      "Storage": "128-256 GB",
      "Battery": "6400 mAh",
      "Gaming Score": 94,
      "Camera Score": 82,
      "Battery Score": 96
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy M55s",
      "Price (₹)": "19,999",
      "Processor": "Snapdragon 7 Gen 1",
      "RAM": "8 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 82,
      "Camera Score": 78,
      "Battery Score": 78
    },
    {
      "Brand": "Vivo",
      "Model": "V40 Lite 5G",
      "Price (₹)": "24,999",
      "Processor": "Snapdragon 4 Gen 2",
      "RAM": "8 GB",
      "Storage": "256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 70,
      "Camera Score": 80,
      "Battery Score": 78
    },
    {
      "Brand": "Realme",
      "Model": "12 Pro+",
      "Price (₹)": "27,999",
      "Processor": "Snapdragon 7s Gen 2",
      "RAM": "8-12 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 84,
      "Camera Score": 92,
      "Battery Score": 78
    },
    {
      "Brand": "OnePlus",
      "Model": "Nord 5",
      "Price (₹)": "31,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "8-12 GB",
      "Storage": "256-512 GB",
      "Battery": "5500 mAh",
      "Gaming Score": 92,
      "Camera Score": 85,
      "Battery Score": 88
    },
    {
      "Brand": "Realme",
      "Model": "GT 6T",
      "Price (₹)": "30,999",
      "Processor": "Snapdragon 7+ Gen 3",
      "RAM": "8-12 GB",
      "Storage": "256-512 GB",
      "Battery": "5500 mAh",
      "Gaming Score": 93,
      "Camera Score": 84,
      "Battery Score": 88
    },
    {
      "Brand": "POCO",
      "Model": "F6",
      "Price (₹)": "29,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "8-12 GB",
      "Storage": "256-512 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 94,
      "Camera Score": 84,
      "Battery Score": 80
    },
    {
      "Brand": "Motorola",
      "Model": "Edge 60 Pro",
      "Price (₹)": "32,999",
      "Processor": "Dimensity 8350 Extreme",
      "RAM": "8-12 GB",
      "Storage": "256-512 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 90,
      "Camera Score": 90,
      "Battery Score": 92
    },
    {
      "Brand": "Vivo",
      "Model": "T4 Pro 5G",
      "Price (₹)": "25,999",
      "Processor": "Snapdragon 7 Gen 3",
      "RAM": "8-12 GB",
      "Storage": "256 GB",
      "Battery": "5500 mAh",
      "Gaming Score": 88,
      "Camera Score": 82,
      "Battery Score": 88
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy A55",
      "Price (₹)": "32,999",
      "Processor": "Exynos 1480",
      "RAM": "8-12 GB",
      "Storage": "128-256 GB",
      "Battery": "5000 mAh",
      "Gaming Score": 85,
      "Camera Score": 88,
      "Battery Score": 80
    },
    {
      "Brand": "iQOO",
      "Model": "13",
      "Price (₹)": "54,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12-16 GB",
      "Storage": "256-512 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 98,
      "Camera Score": 90,
      "Battery Score": 92
    },
    {
      "Brand": "Nothing",
      "Model": "Phone 2",
      "Price (₹)": "29,999",
      "Processor": "Snapdragon 8+ Gen 1",
      "RAM": "8-12 GB",
      "Storage": "128-512 GB",
      "Battery": "4700 mAh",
      "Gaming Score": 90,
      "Camera Score": 85,
      "Battery Score": 72
    },
    {
      "Brand": "OnePlus",
      "Model": "14R",
      "Price (₹)": "39,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12-16 GB",
      "Storage": "256-512 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 97,
      "Camera Score": 88,
      "Battery Score": 92
    },
    {
      "Brand": "Xiaomi",
      "Model": "15",
      "Price (₹)": "64,999",
      "Processor": "Snapdragon 8 Elite",
      "RAM": "12-16 GB",
      "Storage": "256-512 GB",
      "Battery": "5400 mAh",
      "Gaming Score": 98,
      "Camera Score": 93,
      "Battery Score": 88
    },
    {
      "Brand": "Vivo",
      "Model": "V50 Pro",
      "Price (₹)": "44,999",
      "Processor": "Dimensity 9300+",
      "RAM": "12 GB",
      "Storage": "256-512 GB",
      "Battery": "6000 mAh",
      "Gaming Score": 95,
      "Camera Score": 92,
      "Battery Score": 92
    },
    {
      "Brand": "Honor",
      "Model": "200 Pro",
      "Price (₹)": "49,999",
      "Processor": "Snapdragon 8s Gen 3",
      "RAM": "12 GB",
      "Storage": "512 GB",
      "Battery": "5200 mAh",
      "Gaming Score": 92,
      "Camera Score": 95,
      "Battery Score": 84
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 16 Pro Max",
      "Price (₹)": "1,44,900",
      "Processor": "A18 Pro",
      "RAM": "8 GB",
      "Storage": "256 GB-1 TB",
      "Battery": "4685 mAh",
      "Gaming Score": 95,
      "Camera Score": 98,
      "Battery Score": 80
    },
    {
      "Brand": "Google",
      "Model": "Pixel 9 Pro",
      "Price (₹)": "1,09,999",
      "Processor": "Tensor G4",
      "RAM": "16 GB",
      "Storage": "128 GB-1 TB",
      "Battery": "4700 mAh",
      "Gaming Score": 88,
      "Camera Score": 97,
      "Battery Score": 78
    },
    {
      "Brand": "Google",
      "Model": "Pixel 9 Pro Fold",
      "Price (₹)": "1,72,999",
      "Processor": "Tensor G4",
      "RAM": "16 GB",
      "Storage": "256-512 GB",
      "Battery": "4650 mAh",
      "Gaming Score": 89,
      "Camera Score": 96,
      "Battery Score": 76
    },
    {
      "Brand": "Samsung",
      "Model": "Galaxy Z Flip6",
      "Price (₹)": "1,09,999",
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12 GB",
      "Storage": "256-512 GB",
      "Battery": "4000 mAh",
      "Gaming Score": 93,
      "Camera Score": 90,
      "Battery Score": 65
    },
    {
      "Brand": "Apple",
      "Model": "iPhone 17",
      "Price (₹)": "89,900",
      "Processor": "A19",
      "RAM": "8 GB",
      "Storage": "128-512 GB",
      "Battery": "~3600 mAh",
      "Gaming Score": 94,
      "Camera Score": 92,
      "Battery Score": 70
    }
  ]
};

